version: "3.8"

services:
  # ---------------- SeaweedFS ----------------

  seaweed-master:
    image: chrislusf/seaweedfs:latest
    container_name: seaweed-master
    command: master -ip=seaweed-master -port=9333 -mdir=/data
    ports:
      - "9333:9333"
    volumes:
      - seaweed_master_data:/data
    user: "1000:1000"  # 替换为你宿主机的 UID:GID
    networks:
      - airflow_net

  seaweed-filer:
    image: chrislusf/seaweedfs:latest
    container_name: seaweed-filer
    command: filer -master=seaweed-master:9333 -port=8888
    ports:
      - "8888:8888"
      - "18888:18888"
    depends_on:
      - seaweed-master
    networks:
      - airflow_net

  seaweed-s3:
    image: chrislusf/seaweedfs:latest
    container_name: seaweed-s3
    command: s3 -filer=seaweed-filer:8888 -port=8333 
    ports:
      - "8333:8333"
    depends_on:
      - seaweed-filer
    networks:
      - airflow_net

  seaweed-volume:
    image: chrislusf/seaweedfs:latest
    container_name: seaweed-volume
    command: volume -mserver=seaweed-master:9333 -port=8080 -dir=/data
    ports:
      - "8080:8080"
    volumes:
      - seaweed_volume_data:/data
    depends_on:
      - seaweed-master
    networks:
      - airflow_net

  # ---------------- Database ----------------

  postgres:
    image: postgres:13
    container_name: airflow-db
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - airflow_net

  # ---------------- Airflow ----------------

  airflow:
    user: "0:0"
    build:
      context: ./airflow
      dockerfile: Dockerfile
    container_name: airflow
    ports:
      - "8088:8080"
    depends_on:
      - postgres
      - seaweed-s3

    # GPU support (docker-compose compatible)
    # device_requests:
    #   - driver: nvidia
    #     count: 1
    #     capabilities: [gpu]

    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      # AIRFLOW__CORE__FERNET_KEY: ${FERNET_KEY}
      AIRFLOW__CORE__FERNET_KEY: "6Zq8PpWflUoF8RCHvQB5NOYL9qnR1JV6FOYWsz84wbQ="
      AIRFLOW__LOGGING__REMOTE_LOGGING: "true"
      AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER: s3://airflow-bucket/logs
      AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID: seaweed_s3

      AWS_ACCESS_KEY_ID: anykey
      AWS_SECRET_ACCESS_KEY: anysecret

    command: >
      bash -c "
      airflow db migrate &&
      airflow users create
        --username admin
        --password admin
        --firstname Admin
        --lastname User
        --role Admin
        --email admin@example.com || true &&

      until curl -sf http://seaweed-s3:8333; do sleep 2; done &&
      curl -X PUT http://seaweed-s3:8333/6gdali-lake2026 || true &&

      airflow connections add 'seaweed_s3'
        --conn-type 'aws'
        --conn-login 'anykey'
        --conn-password 'anysecret'
        --conn-extra '{\"endpoint_url\": \"http://seaweed-s3:8333\", \"region_name\": \"us-east-1\"}' || true &&

      airflow scheduler & exec airflow webserver
      "
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      # - ./airflow/logs:/opt/airflow/logs
      # - ./airflow/plugins:/opt/airflow/plugins
      - /var/run/docker.sock:/var/run/docker.sock


    networks:
      - airflow_net

# ---------------- Networks ----------------

networks:
  airflow_net:
    driver: bridge

# ---------------- Volumes ----------------

volumes:
  pgdata:
  seaweed_master_data:
  seaweed_volume_data:
